name: Windows MSVC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  msvc2019:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [Win32, x64]
        standard: [11, 14, 17, 20]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G"Visual Studio 16 2019" -A ${{ matrix.architecture }} -DCMAKE_CXX_FLAGS="/W4 /WX" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_STANDARD=${{ matrix.standard }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
